//! The turn contract.
//!
//! The types are generated from `nervous_system/proto/turn.proto`; what is here is the
//! convenience of building and reading them.
//!
//! A harness process owns no durable state. It starts, claims its turn, and receives one
//! [`TurnContext`] holding everything it needs. Every write it sends back carries the turn id
//! and the epoch it was handed, and the core refuses anything from a stale epoch. That is what
//! makes a re-run of the same turn either a no-op or a clean refusal, never half-applied.

use serde::{Deserialize, Serialize};
use serde_json::Value;

pub use crate::pb::wire::{Message, SignalKind, ToolSchema, TurnContext, TurnOutcome};

/// Opaque, sortable, unique per turn. Generated by the core only.
pub type TurnId = String;

/// Bumped by the core whenever a turn ends or is cancelled. A write tagged with an old epoch
/// is rejected, which is how a stranded process from a previous life is kept harmless.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
#[serde(transparent)]
pub struct Epoch(pub u32);

impl Epoch {
    pub fn next(self) -> Epoch {
        Epoch(self.0 + 1)
    }
}

impl std::fmt::Display for Epoch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

impl SignalKind {
    /// The short name used on disk and in events. Not the schema's own spelling, which is
    /// `SIGNAL_USER`: the journal has read `user` since before there was a schema, and the
    /// learning passes parse it.
    pub fn as_str(&self) -> &'static str {
        match self {
            SignalKind::SignalUser | SignalKind::SignalUnspecified => "user",
            SignalKind::SignalCommand => "command",
            SignalKind::SignalFocus => "focus",
            SignalKind::SignalThoughtDone => "thought_done",
            SignalKind::SignalReminder => "reminder",
            SignalKind::SignalAlarm => "alarm",
            SignalKind::SignalNote => "note",
            SignalKind::SignalExpired => "expired",
            SignalKind::SignalIdle => "idle",
        }
    }

    pub fn parse(s: &str) -> Option<SignalKind> {
        Some(match s {
            "user" => SignalKind::SignalUser,
            "command" => SignalKind::SignalCommand,
            "focus" => SignalKind::SignalFocus,
            "thought_done" => SignalKind::SignalThoughtDone,
            "reminder" => SignalKind::SignalReminder,
            "alarm" => SignalKind::SignalAlarm,
            "note" => SignalKind::SignalNote,
            "expired" => SignalKind::SignalExpired,
            "idle" => SignalKind::SignalIdle,
            _ => return None,
        })
    }

    /// Whether this came from a person. Only these reach the mind unframed.
    pub fn is_human(&self) -> bool {
        matches!(self, SignalKind::SignalUser | SignalKind::SignalCommand)
    }

    /// Lower sorts first out of the queue. A person always jumps it.
    pub fn priority(&self) -> u8 {
        match self {
            SignalKind::SignalUser | SignalKind::SignalCommand | SignalKind::SignalUnspecified => 0,
            SignalKind::SignalFocus | SignalKind::SignalThoughtDone | SignalKind::SignalNote => 1,
            SignalKind::SignalReminder | SignalKind::SignalAlarm | SignalKind::SignalExpired => 2,
            SignalKind::SignalIdle => 3,
        }
    }
}

impl Message {
    pub fn user(content: impl Into<String>) -> Self {
        Message { role: "user".into(), content: Some(content.into()), ..Default::default() }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Message { role: "assistant".into(), content: Some(content.into()), ..Default::default() }
    }

    pub fn system(content: impl Into<String>) -> Self {
        Message { role: "system".into(), content: Some(content.into()), ..Default::default() }
    }

    pub fn tool(name: impl Into<String>, result: impl Into<String>) -> Self {
        Message {
            role: "tool".into(),
            content: Some(result.into()),
            name: Some(name.into()),
            ..Default::default()
        }
    }

    pub fn text(&self) -> &str {
        self.content.as_deref().unwrap_or("")
    }

    /// The tool calls on this message, as ordinary JSON.
    pub fn calls(&self) -> Option<Value> {
        self.tool_calls.as_ref().map(crate::frame::from_list)
    }

    pub fn with_calls(mut self, calls: Value) -> Self {
        self.tool_calls = crate::frame::to_list(calls);
        self
    }

    /// An assistant message that is nothing but a tool call carries no prose worth learning.
    pub fn is_tool_call_only(&self) -> bool {
        self.role == "assistant" && self.tool_calls.is_some() && self.text().trim().is_empty()
    }
}

impl TurnContext {
    /// What woke the mind, as the enum rather than its number.
    pub fn signal(&self) -> SignalKind {
        SignalKind::try_from(self.kind).unwrap_or(SignalKind::SignalUnspecified)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_person_outranks_everything_else() {
        assert!(SignalKind::SignalUser.priority() < SignalKind::SignalFocus.priority());
        assert!(SignalKind::SignalFocus.priority() < SignalKind::SignalAlarm.priority());
        assert!(SignalKind::SignalAlarm.priority() < SignalKind::SignalIdle.priority());
    }

    #[test]
    fn only_people_are_unframed() {
        assert!(SignalKind::SignalUser.is_human());
        assert!(SignalKind::SignalCommand.is_human());
        for k in [SignalKind::SignalIdle, SignalKind::SignalAlarm, SignalKind::SignalFocus,
                  SignalKind::SignalExpired] {
            assert!(!k.is_human(), "{} should be framed", k.as_str());
        }
    }

    #[test]
    fn the_short_names_used_on_disk_round_trip() {
        for k in [SignalKind::SignalUser, SignalKind::SignalCommand, SignalKind::SignalFocus,
                  SignalKind::SignalThoughtDone, SignalKind::SignalReminder, SignalKind::SignalAlarm,
                  SignalKind::SignalNote, SignalKind::SignalExpired, SignalKind::SignalIdle] {
            assert_eq!(SignalKind::parse(k.as_str()), Some(k), "{} did not round trip", k.as_str());
        }
        assert_eq!(SignalKind::parse("from_the_future"), None);
    }

    #[test]
    fn epochs_only_move_forward() {
        let e = Epoch(4);
        assert!(e.next() > e);
    }

    #[test]
    fn a_bare_tool_call_is_recognised() {
        let m = Message::assistant("").with_calls(serde_json::json!([{"name": "shell"}]));
        assert!(m.is_tool_call_only());
        let m2 = Message::assistant("let me look").with_calls(serde_json::json!([{"name": "shell"}]));
        assert!(!m2.is_tool_call_only());
        assert_eq!(m.calls().unwrap()[0]["name"], "shell");
    }

    #[test]
    fn a_message_without_content_reads_as_empty_not_null() {
        let m: Message = serde_json::from_str(r#"{"role":"assistant"}"#).unwrap();
        assert_eq!(m.text(), "");
    }

    #[test]
    fn a_message_keeps_the_field_names_the_journal_already_uses() {
        let mut m = Message::user("hello");
        m.kind = Some("user".into());
        m.turn = Some("01789-0001".into());
        let j = serde_json::to_string(&m).unwrap();
        assert_eq!(j, r#"{"role":"user","content":"hello","kind":"user","turn":"01789-0001"}"#);
    }
}
