//! The turn contract.
//!
//! A harness process owns no durable state. It starts, claims its turn, and receives one
//! [`TurnContext`] holding everything it needs. Every write it sends back carries the turn id
//! and the epoch it was handed, and the core refuses anything from a stale epoch. That is what
//! makes a re-run of the same turn either a no-op or a clean refusal, never a half-application.

use serde::{Deserialize, Serialize};
use serde_json::Value;

/// Opaque, sortable, unique per turn. Generated by the core only.
pub type TurnId = String;

/// Bumped by the core whenever a turn ends or is cancelled. A write tagged with an old epoch
/// is rejected, which is how a stranded process from a previous life is kept harmless.
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Serialize, Deserialize, Default)]
#[serde(transparent)]
pub struct Epoch(pub u64);

impl Epoch {
    pub fn next(self) -> Epoch {
        Epoch(self.0 + 1)
    }
}

impl std::fmt::Display for Epoch {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{}", self.0)
    }
}

/// What kind of nudge woke the mind. Determines how the text is framed before it is shown.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SignalKind {
    /// A human said something. The only kind that reaches the mind unframed.
    User,
    /// A mentor command echoed into the conversation.
    Command,
    /// An inner thought calling back to the main thread.
    Focus,
    /// An inner thought reporting that it is done.
    ThoughtDone,
    /// An inner thought's periodic progress note. No reply is expected.
    Reminder,
    /// An alarm the mind set earlier.
    Alarm,
    /// A note the mind left for itself.
    Note,
    /// A question that was never answered and has run out of time.
    Expired,
    /// Nothing happened for a while.
    Idle,
}

impl SignalKind {
    /// Whether this signal came from a person. Only these are shown verbatim.
    pub fn is_human(&self) -> bool {
        matches!(self, SignalKind::User | SignalKind::Command)
    }

    pub fn as_str(&self) -> &'static str {
        match self {
            SignalKind::User => "user",
            SignalKind::Command => "command",
            SignalKind::Focus => "focus",
            SignalKind::ThoughtDone => "thought_done",
            SignalKind::Reminder => "reminder",
            SignalKind::Alarm => "alarm",
            SignalKind::Note => "note",
            SignalKind::Expired => "expired",
            SignalKind::Idle => "idle",
        }
    }

    /// Lower sorts first out of the mailbox. A person always jumps the queue.
    pub fn priority(&self) -> u8 {
        match self {
            SignalKind::User | SignalKind::Command => 0,
            SignalKind::Focus | SignalKind::ThoughtDone | SignalKind::Note => 1,
            SignalKind::Reminder | SignalKind::Alarm | SignalKind::Expired => 2,
            SignalKind::Idle => 3,
        }
    }
}

/// One message in the conversation, as it is journalled and as it is sent to the model.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct Message {
    pub role: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub content: Option<String>,
    /// Present on an assistant message that called tools.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub tool_calls: Option<Value>,
    /// Present on a tool result: which tool produced it.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub args: Option<Value>,
    /// On a user message, which kind of signal it came from.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub kind: Option<String>,
}

impl Message {
    pub fn user(content: impl Into<String>) -> Self {
        Message { role: "user".into(), content: Some(content.into()), tool_calls: None, name: None, args: None, kind: None }
    }

    pub fn assistant(content: impl Into<String>) -> Self {
        Message { role: "assistant".into(), content: Some(content.into()), tool_calls: None, name: None, args: None, kind: None }
    }

    pub fn system(content: impl Into<String>) -> Self {
        Message { role: "system".into(), content: Some(content.into()), tool_calls: None, name: None, args: None, kind: None }
    }

    pub fn tool(name: impl Into<String>, result: impl Into<String>) -> Self {
        Message { role: "tool".into(), content: Some(result.into()), tool_calls: None, name: Some(name.into()), args: None, kind: None }
    }

    pub fn text(&self) -> &str {
        self.content.as_deref().unwrap_or("")
    }

    /// An assistant message that is nothing but a tool call carries no prose worth learning.
    pub fn is_tool_call_only(&self) -> bool {
        self.role == "assistant" && self.tool_calls.is_some() && self.text().trim().is_empty()
    }
}

/// A tool as the model sees it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ToolSchema {
    pub name: String,
    pub description: String,
    pub parameters: Value,
}

/// Everything one turn needs, handed over in a single reply.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TurnContext {
    pub turn: TurnId,
    pub epoch: Epoch,
    pub kind: SignalKind,
    /// What arrived, unframed. Kept for the record and for events.
    pub text: String,
    /// What the mind actually reads, after framing.
    pub framed: String,
    /// The identity prompt in force for this turn.
    pub system: String,
    /// The conversation so far, complete exchanges only, oldest first.
    pub window: Vec<Message>,
    /// How many tool rounds this turn may take before it is cut off.
    pub max_rounds: u32,
    /// Extra metadata carried from the signal, such as the originating request id.
    #[serde(default)]
    pub meta: Value,
}

/// How a turn ended. Reported back so the core can journal it and score it.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct TurnOutcome {
    pub turn: TurnId,
    pub epoch: Epoch,
    pub final_text: String,
    /// Sensor observations the limbic system reads: repeated calls, tool errors, exhaustion.
    #[serde(default)]
    pub flags: Vec<String>,
    #[serde(default)]
    pub tools_used: u32,
    #[serde(default)]
    pub seconds: f64,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_person_outranks_everything_else() {
        assert!(SignalKind::User.priority() < SignalKind::Focus.priority());
        assert!(SignalKind::Focus.priority() < SignalKind::Alarm.priority());
        assert!(SignalKind::Alarm.priority() < SignalKind::Idle.priority());
    }

    #[test]
    fn only_people_are_unframed() {
        assert!(SignalKind::User.is_human());
        assert!(SignalKind::Command.is_human());
        for k in [SignalKind::Idle, SignalKind::Alarm, SignalKind::Focus, SignalKind::Expired] {
            assert!(!k.is_human(), "{} should be framed", k.as_str());
        }
    }

    #[test]
    fn signal_kinds_serialise_to_their_wire_names() {
        let j = serde_json::to_string(&SignalKind::ThoughtDone).unwrap();
        assert_eq!(j, "\"thought_done\"");
        assert_eq!(serde_json::from_str::<SignalKind>("\"idle\"").unwrap(), SignalKind::Idle);
    }

    #[test]
    fn epochs_only_move_forward() {
        let e = Epoch(4);
        assert!(e.next() > e);
    }

    #[test]
    fn a_bare_tool_call_is_recognised() {
        let mut m = Message::assistant("");
        m.tool_calls = Some(serde_json::json!([{"name": "shell"}]));
        assert!(m.is_tool_call_only());
        let mut m2 = Message::assistant("let me look");
        m2.tool_calls = Some(serde_json::json!([{"name": "shell"}]));
        assert!(!m2.is_tool_call_only());
    }

    #[test]
    fn a_message_without_content_reads_as_empty_not_null() {
        let m: Message = serde_json::from_str(r#"{"role":"assistant"}"#).unwrap();
        assert_eq!(m.text(), "");
    }
}
