# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: wire.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nwire.proto\x12\ngroow.wire\x1a\x1cgoogle/protobuf/struct.proto\"\xdc\x01\n\x05\x46rame\x12\"\n\x03req\x18\x01 \x01(\x0b\x32\x13.groow.wire.RequestH\x00\x12 \n\x04part\x18\x02 \x01(\x0b\x32\x10.groow.wire.PartH\x00\x12 \n\x03rep\x18\x03 \x01(\x0b\x32\x11.groow.wire.ReplyH\x00\x12\"\n\x03\x65rr\x18\x04 \x01(\x0b\x32\x13.groow.wire.FailureH\x00\x12\x1f\n\x02\x65v\x18\x05 \x01(\x0b\x32\x11.groow.wire.EventH\x00\x12 \n\x04push\x18\x06 \x01(\x0b\x32\x10.groow.wire.PushH\x00\x42\x04\n\x02of\"G\n\x07Request\x12\n\n\x02id\x18\x01 \x01(\r\x12\n\n\x02op\x18\x02 \x01(\t\x12$\n\x03\x61rg\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"9\n\x04Part\x12\n\n\x02id\x18\x01 \x01(\r\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct\"7\n\x05Reply\x12\n\n\x02id\x18\x01 \x01(\r\x12\"\n\x02ok\x18\x02 \x01(\x0b\x32\x16.google.protobuf.Value\"B\n\x07\x46\x61ilure\x12\n\n\x02id\x18\x01 \x01(\r\x12\x1e\n\x04\x63ode\x18\x02 \x01(\x0e\x32\x10.groow.wire.Code\x12\x0b\n\x03msg\x18\x03 \x01(\t\"G\n\x05\x45vent\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\t\n\x01t\x18\x02 \x01(\x01\x12%\n\x04\x64\x61ta\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\";\n\x04Push\x12\x0c\n\x04name\x18\x01 \x01(\t\x12%\n\x04\x64\x61ta\x18\x02 \x01(\x0b\x32\x17.google.protobuf.Struct*\xc3\x01\n\x04\x43ode\x12\x14\n\x10\x43ODE_UNSPECIFIED\x10\x00\x12\x13\n\x0f\x43ODE_UNKNOWN_OP\x10\x01\x12\x10\n\x0c\x43ODE_BAD_ARG\x10\x02\x12\x0f\n\x0b\x43ODE_DENIED\x10\x03\x12\x14\n\x10\x43ODE_STALE_EPOCH\x10\x04\x12\x12\n\x0e\x43ODE_NOT_FOUND\x10\x05\x12\r\n\tCODE_IDLE\x10\x06\x12\r\n\tCODE_BUSY\x10\x07\x12\x12\n\x0e\x43ODE_CANCELLED\x10\x08\x12\x11\n\rCODE_INTERNAL\x10\t*N\n\x04Role\x12\x14\n\x10ROLE_UNSPECIFIED\x10\x00\x12\x0e\n\nROLE_AGENT\x10\x01\x12\x0f\n\x0bROLE_VIEWER\x10\x02\x12\x0f\n\x0bROLE_MENTOR\x10\x03\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'wire_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CODE._serialized_start=671
  _CODE._serialized_end=866
  _ROLE._serialized_start=868
  _ROLE._serialized_end=946
  _FRAME._serialized_start=57
  _FRAME._serialized_end=277
  _REQUEST._serialized_start=279
  _REQUEST._serialized_end=350
  _PART._serialized_start=352
  _PART._serialized_end=409
  _REPLY._serialized_start=411
  _REPLY._serialized_end=466
  _FAILURE._serialized_start=468
  _FAILURE._serialized_end=534
  _EVENT._serialized_start=536
  _EVENT._serialized_end=607
  _PUSH._serialized_start=609
  _PUSH._serialized_end=668
# @@protoc_insertion_point(module_scope)
